/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAvatar: typeof import('tdesign-vue-next')['Avatar']
    TButton: typeof import('tdesign-vue-next')['Button']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TFooter: typeof import('tdesign-vue-next')['Footer']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    THeader: typeof import('tdesign-vue-next')['Header']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TOption: typeof import('tdesign-vue-next')['Option']
    TPagination: typeof import('tdesign-vue-next')['Pagination']
    TPopconfirm: typeof import('tdesign-vue-next')['Popconfirm']
    TRadio: typeof import('tdesign-vue-next')['Radio']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSwiper: typeof import('tdesign-vue-next')['Swiper']
    TSwiperItem: typeof import('tdesign-vue-next')['SwiperItem']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    TTable: typeof import('tdesign-vue-next')['Table']
    TTag: typeof import('tdesign-vue-next')['Tag']
    TTextarea: typeof import('tdesign-vue-next')['Textarea']
    TUpload: typeof import('tdesign-vue-next')['Upload']
  }
}
